apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: registry-secret
spec:
  encryptedData:
    .dockerconfigjson: AgBz6XbsNQTdsZbG9SdP+mJt1yf/f9qXG8x6LHUsxtJASRCnKLOyi7oH2DuNC574bmgV+slBLprM7F9GevbOLqZBJ03+1+4UtaC243oTNfPBpFt9A8GIvnkemD0IOnvduW8xL8Nam3SCxKovhV7oyksqAy7N1V46hyMlTVxdzicpM2Zgkrg45wTL+uFflgKJ9tlEs6vuHAsSiWoKi83vrFGmmtzJquHWczKqxnrRcTFk5bihHHtYSzaHqidA1kL6ucWT3pZGaf/8t5TArf4oky08vv8FFyb+OGlMHse1R+P6o6HqnlhC8f+JM4x0PGY+NRPk9vaRg16ieKFD0myrnzkEsAkeROZ7HxBVCa7jUOrpfqTO1OhwMaKm7cOEUbuaIDzWO6naRmSOcveoJmPTt5GZZgKOAt5rxCmCyMV2+2vyXXEsGwkiu51eJpsn51sSHPww6eZqIwSrYeGNgd/ZFSGKzZ4tEQJJXSR+zqgAihhlxa2qiOj93lLMdakvY7hNiGT6l/2FeTxI+bejsu5Z5UCnZugRwvZFGElm3sYfFTo9OiCd5iHJTaT9K6dU9Qoiv/lA+N+bYcpzwYEMnTbxjQL3tgRF7FOPrQla6ytr3MEiiwfz5H9F9w/DegYJw48bCQvkTrpdXCEI+gMX6MJ1guT4prnmvstX4wu+Q1DxyPfMImAiwmYcPfWBiZV/37UX7GqyLyMFEdCFoCtM41cxlTm4L9ZkxNKorP43yrjVNdRIaIptLn1hS73fYnEmvHDTZ5tWY1Dsw9RSbhHBJpFQ1xoqbce6KMp8bxzOSXG/P6OdoIf5qjlOniL2ToJM+/eiMNGJQX2P9NZZk53ced963tte1xZiFRj4cSgDJH2wNSLBwc44qJ/kyXsyEGypS2gvimZAd3/d1ysHFLxVhTeULlpXIVVtnQk36P1RAJaso6t3zB5VPIA174bxgbKCgcdK1vxPjv/O27glZI2jWewuIBMnsgYdPEzmS2dgxRlQ9g7/N6ropm0HORj/xZhG8ZcYOg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: registry-secret
    type: kubernetes.io/dockerconfigjson

