apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flamingops-ui.name" . }}
  labels:
  {{- include "flamingops-ui.labels" . | nindent 4 }}
data:
  API_URL: {{ .Values.config.plainText.api.url | quote }}
  API_URL_LOC: {{ .Values.config.plainText.api.urlLoc | quote }}