apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flamingops-ui.name" . }}-entrypoint
  labels:
  {{- include "flamingops-ui.labels" . | nindent 4 }}
data:
  entrypoint.sh: |-
    #!/bin/sh

    ROOT_DIR=/usr/share/nginx/html

    # Replace env vars in JavaScript files
    for file in "$ROOT_DIR"/**/*.js*;
    do
      echo "PROCESSING: $file";
      sed -i 's@'${API_URL_LOC}'@'${API_URL}'@g' "$file"
    done

    echo "Starting Nginx"
    nginx -g 'daemon off;'

