apiVersion: v1
kind: Service
metadata:
  name: {{ include "flamingops-ui.name" . }}
  labels: {{- include "flamingops-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector: {{- include "flamingops-ui.selectorLabels" . | nindent 4 }}
