apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flamingops-ui.name" . }}
  labels:
    {{- include "flamingops-ui.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}