version: "3.8"

services:
  sample-api:
    container_name: sample-api
    build:
      context: .
      dockerfile: build/package/sample-api/Dockerfile
      target: dev_build
    ports:
      - 3335:3335
    volumes:
      - ./:/go/src/github.com/blyndusk/flamingops/
    networks:
      - main

  web:
    container_name: web
    build:
      context: .
      dockerfile: build/package/web/Dockerfile.loc
    ports:
      - 3000:3000
    networks:
      - main

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
      - DATABASE_HOST=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - main

  adminer:
    build:
      context: .
      dockerfile: build/package/adminer/Dockerfile
    environment:
      ADMINER_DB: db
      ADMINER_DRIVER: pgsql
      ADMINER_PASSWORD: root
      ADMINER_SERVER: postgres
      ADMINER_USERNAME: root
      ADMINER_AUTOLOGIN: 1
      ADMINER_NAME: Sample DB
    restart: always
    ports:
      - 3334:8080
    depends_on:
      - postgres
    networks:
      - main

volumes:
  postgres:

networks:
  main:
