# - SVC ---------------------------------------------------------------- #
svc:
  type: ClusterIP
  gaApi:
    name: svc-go
    ports:
      - name: svc-go
        protocol: TCP
        port: 80
        targetPort: 8080
  gaApp:
    name: svc-node
    ports:
      - name: svc-node
        protocol: TCP
        port: 80
        targetPort: 80

# - DEPLOY ------------------------------------------------------------- #
deploy:
  replicaCount: 1
  autoscaling:
    enabled: false
  gaApp:
    name: deploy-node
  gaApi:
    name: deploy-go

# - IMAGES ------------------------------------------------------------- #
images:
  pullPolicy: Always
  restartPolicy: Always
  gaApi:
    name: go
    repository: ghcr.io/blyndusk/flamingops_go
    tag: "latest"
    svc:
      name: svc-go
      port: 8080
      protocol: TCP
  gaApp:
    name: node
    repository: ghcr.io/blyndusk/flamingops_node
    tag: "latest"
    svc:
      name: svc-node
      port: 80
      protocol: TCP

# - INGRESS ------------------------------------------------------------ #
ing:
  name: ingress
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: issuer
  hosts:
    - host: api.flamingops.com
      paths:
        - path: /
          pathType: Prefix
          name: svc-go
          port: 80
    - host: flamingops.com
      paths:
        - path: /
          pathType: Prefix
          name: svc-node
          port: 80

# - REGSEC ------------------------------------------------------------- #
regsec:
  name: registry-secret
  type: kubernetes.io/dockerconfigjson
  json: ewoJImF1dGhzIjogewoJCSJkb2NrZXIucGtnLmdpdGh1Yi5jb20iOiB7CgkJCSJhdXRoIjogIllteDVibVIxYzJzNloyaHdYekZ3UlhKblZtVnBTWGhDV1d4V2RVNVViVWhRZUd4MFoyaHNha1JWYURGYWMwRjVVdz09IgoJCX0sCgkJImdoY3IuaW8iOiB7CgkJCSJhdXRoIjogIlJtOW5ieTFEWVhCcGRHRnNPbWRvY0Y5Q1JEZFdhemxNWWtaSVVXdEVUelZDWmxaTFpraDRlVE5DU205cmVFUXdZVzVXVkVjPSIKCQl9Cgl9Cn0=

# - ISSUER ------------------------------------------------------------- #
issuer:
  name: letsencrypt-prod
  email: adelaloy@nextroad.com
  server: https://acme-v02.api.letsencrypt.org/directory

# - CERT --------------------------------------------------------------- #
cert:
  name: certificate
  secret: tls-secret
  dns:
    - api.flamingops.com
    - flamingops.com