apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flamingops-api.name" . }}
  labels:
  {{- include "flamingops-api.labels" . | nindent 4 }}
data:
  env: |-
    DATABASE_HOST={{ .Values.config.plainText.database.host }}
    DATABASE_NAME={{ .Values.config.plainText.database.name }}
    DATABASE_PORT={{ .Values.config.plainText.database.port }}
