apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels: {{- include "flamingops-api.labels" . | nindent 4 }}
  creationTimestamp: null
  name: {{include "flamingops-api.name" . }}
spec:
  encryptedData:
    "DATABASE_PASSWORD":
      {{.Values.config.encrypted.database.password | quote }}
    "DATABASE_USER": {{.Values.config.encrypted.database.user | quote }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels: {{- include "flamingops-api.labels" . | nindent 8 }}
      name: {{include "flamingops-api.name" . }}
