swagger: '2.0'
info:
  description: flamingops base API
  version: 1.0.0
  title: flamingops base API 
  # put the contact info for your development or API team
  contact:
    email: alexandre.delaloy.pro@gmail.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: user
  description: Regular user using web service
- name: web-service
  description: AWS + SCW  
- name: secrets
  description: Secrets used for lambda

paths:
  /login:
    post:
      tags:
      - login
      summary: login   
      operationId: login
      description: |
        Logs an user
      parameters:
      - in: query
        name: username
        description: The user's username
        required: true
        type: string
      - in: query
        name: password
        description: The user's password's hash
        required: true
        type: string
      responses:
        201:
          description: login successful
          
  /secrets:
    post:
      tags:
      - secrets
      summary: secrets 
      operationId: CreateSecret
      description: |
        Create secret
      parameters:
      - in: query
        name: name
        description: The desired name for the secret creation
        required: true
        type: string
      - in: query
        name: secretString
        description: The desired string for the secret creation
        required: true
        type: string
      responses:
        201:
          description: secret request succeed
    put:
      tags:
      - secrets
      summary: secrets 
      operationId: UpdateSecret
      description: |
        Update secret
      parameters:
      - in: query
        name: secretName
        description: The desired name for the secret update
        required: true
        type: string
      - in: query
        name: name
        description: The desired name for the secret update
        required: true
        type: string
      - in: query
        name: secretString
        description: The desired string for the secret update
        required: true
        type: string
      responses:
        201:
          description: secret successfully updated
    delete:
      tags:
      - secrets
      summary: secrets 
      operationId: DeleteSecret
      description: |
        Delete user
      parameters:
      - in: query
        name: secretName
        description: The desired name for the secret update
        required: true
        type: string
      responses:
        201:
          description: secret successfully deleted          

  /user:
    get:
      tags:
      - user
      summary: user 
      operationId: GetUser
      description: |
        Get user by ID
      parameters:
      - in: query
        name: id
        description: The desired id for the requested user
        required: true
        type: string
      responses:
        201:
          description: user request succeed
    post:
      tags:
      - user
      summary: user 
      operationId: CreateUser
      description: |
        Create user
      parameters:
      - in: query
        name: username
        description: The desired username for the created user
        required: true
        type: string
      - in: query
        name: password
        description: The desired password for the created user
        required: true
        type: string
      - in: query
        name: mail
        description: The desired mail for the created user
        required: true
        type: string
      responses:
        201:
          description: user successfully requested
    put:
      tags:
      - user
      summary: user 
      operationId: UpdateUser
      description: |
        Update user
      parameters:
      - in: query
        name: id
        description: The desired id for the updated user
        required: true
        type: string
      - in: query
        name: username
        description: The desired username for the updated user
        required: true
        type: string
      - in: query
        name: password
        description: The desired password for the updated user
        required: true
        type: string
      - in: query
        name: mail
        description: The desired mail for the updated user
        required: true
        type: string
      responses:
        201:
          description: user successfully updated
    delete:
      tags:
      - user
      summary: user 
      operationId: DeleteUser
      description: |
        Delete user
      parameters:
      - in: query
        name: id
        description: The desired id for the requested user
        required: true
        type: string
      responses:
        201:
          description: user successfully deleted
        
        
  /user/requested-regions:
    get:
      tags:
      - user
      summary: user 
      operationId: GetUserRequestedRegions
      description: |
        Get region by user ID
      parameters:
      - in: query
        name: user_id
        description: The desired user id for the requested region
        required: true
        type: string
      responses:
        201:
          description: region request succeed
    put:
      tags:
      - user
      summary: user 
      operationId: UpdateUserRequestedRegions
      description: |
        Update region
      parameters:
      - in: query
        name: user_id
        description: The desired id for the requested region
        required: true
        type: string
      responses:
        201:
          description: region successfully updated
    delete:
      tags:
      - user
      summary: user 
      operationId: DeleteUserRequestedRegions
      description: |
        Delete region
      parameters:
      - in: query
        name: user_id
        description: The desired id for the requested region
        required: true
        type: string
      responses:
        201:
          description: region successfully deleted
        
  /user/active-services:
    get:
      tags:
      - user
      summary: user 
      operationId: GetUserActiveService
      description: |
        Get active service by ID
      parameters:
      - in: query
        name: user_id
        description: The desired user id for the active service
        required: true
        type: string
      responses:
        201:
          description: active service request succeed
    put:
      tags:
      - user
      summary: user 
      operationId: UpdateUserActiveService
      description: |
        Update active service
      parameters:
      - in: query
        name: user_id
        description: The desired id for the active service
        required: true
        type: string
      responses:
        201:
          description: active service successfully updated
    delete:
      tags:
      - user
      summary: user 
      operationId: DeleteUserActiveService
      description: |
        Delete user
      parameters:
      - in: query
        name: user_id
        description: The desired id for the active service
        required: true
        type: string
      responses:
        201:
          description: active service successfully deleted
        
  /user/aws-service-data:
    get:
      tags:
      - web-service
      summary: web-service
      operationId: GetAwsServiceData
        Get AWS service data by ID
      parameters:
      - in: query
        name: user_id
        description: The desired user id for the AWS service data
        required: true
        type: string
      responses:
        201:
          description: AWS service data request succeed
    delete:
      tags:
      - web-service
      summary: web-service 
      operationId: DeleteAwsServiceData
      description: |
        Delete user
      parameters:
      - in: query
        name: user_id
        description: The desired id for the active serAWS service datavice
        required: true
        type: string
      responses:
        201:
          description: AWS service data successfully deleted
        
  /user/sw-service-data:
    get:
      tags:
      - web-service
      summary: web-service
      operationId: GetScwServiceData
      description: |
        Get SCW service data by ID
      parameters:
      - in: query
        name: user_id
        description: The desired user id for the SCW service data
        required: true
        type: string
      responses:
        201:
          description: SCW service data request succeed
    delete:
      tags:
      - web-service
      summary: web-service 
      operationId: DeleteScwServiceData
      description: |
        Delete user
      parameters:
      - in: query
        name: user_id
        description: The desired id for the SCW service data
        required: true
        type: string
      responses:
        201:
          description: SCW service data successfully deleted
        
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /Flamingo8/flamingops_base_api/1.0.0
schemes:
 - https