swagger: '2.0'
info:
  description: flamingops base API
  version: 1.0.0
  title: flamingops base API 
  # put the contact info for your development or API team
  contact:
    email: alexandre.delaloy.pro@gmail.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: users
  description: Regular user using web service

paths:
  /register:
    post:
      tags:
      - users
      summary: register 
      operationId: register
      description: |
        Registers a new user
      parameters:
      - in: query
        name: username
        description: The desired username for the new user
        required: true
        type: string
      - in: query
        name: mail
        description: The desired mail for the new user
        required: true
        type: string        
      - in: query
        name: password
        description: The desired password's hash for the new user
        required: true
        type: string
      responses:
        201:
          description: user created
        400:
          description: invalid input, object invalid
        409:
          description: an existing user already exists
  /login:
    post:
      tags:
      - users
      summary: login   
      operationId: login
      description: |
        Logs an user
      parameters:
      - in: query
        name: username
        description: The user's usernam
        required: true
        type: string
      - in: query
        name: password
        description: The user's password's hash
        required: true
        type: string
      responses:
        201:
          description: login successful
        400:
          description: invalid input, object invalid
  /user/update:
    put:
      tags:
      - users
      summary: update user 
      operationId: userUpdate
      description: |
        Registers a new user
      parameters:
      - in: query
        name: id
        description: The requested user's id
        required: true
        type: integer
      - in: query
        name: username
        description: The desired username for the updated user
        required: false
        type: string
      - in: query
        name: mail
        description: The desired mail for the updated user
        required: false
        type: string        
      - in: query
        name: password
        description: The desired password's hash for the updated user
        required: false
        type: string
      responses:
        201:
          description: user updated
        400:
          description: invalid input, object invalid
          
  /user/providers:
    post:
      tags:
      - users
      summary: create provider connection
      operationId: createProvider
      description: |
        Registers a new provider connection
      parameters:
      - in: query
        name: id
        description: The requested user's id
        required: true
        type: integer
      - in: query
        name: provider
        description: The requested provider
        required: true
        type: string
      - in: query
        name: credentials
        description: The required credentials
        required: true
        type: array
        items: {}
      responses:
        201:
          description: provider connection created
        400:
          description: invalid input, object invalid
        
    put:
      tags:
      - users
      summary: update provider connection
      operationId: updateProvider
      description: |
        Updates an existing provider connection
      parameters:
      - in: query
        name: id
        description: The requested user's id
        required: true
        type: integer
      - in: query
        name: provider
        description: The requested provider
        required: true
        type: string
      - in: query
        name: credentials
        description: The required credentials
        required: true
        type: array
        items: {}
      responses:
        201:
          description: provider connection updated
        400:
          description: invalid input, object invalid
          
    delete:
      tags:
      - users
      summary: delete provider connection
      operationId: deleteProvider
      description: |
        Deletes an existing provider connection
      parameters:
      - in: query
        name: id
        description: The requested user's id
        required: true
        type: integer
      - in: query
        name: provider
        description: The requested provider
        required: true
        type: string
      responses:
        201:
          description: provider connection deleted
        400:
          description: invalid input, object invalid
          
  /active-services:
    get:
      tags:
      - users
      summary: get active services
      operationId: getActiveServices
      description: |
        Gets all users' active services
      parameters:
      - in: query
        name: id
        description: The requested user's id
        required: true
        type: integer
      responses:
        201:
          description: provider connection created
        400:
          description: invalid input, object invalid
  
  /active-services/refresh:
    post:
      tags:
      - users
      summary: refresh active services
      operationId: refreshActiveServices
      description: |
        Sends a job to the workers queue
      parameters:
      - in: query
        name: id
        description: The requested user's id
        required: true
        type: integer
      responses:
        201:
          description: job successfully sent
        400:
          description: invalid input, object invalid

  /active-services/check-update:
    get:
      tags:
      - users
      summary: check user status
      operationId: checkUserStatus
      description: |
        Sends a job to the workers queue
      parameters:
      - in: query
        name: id
        description: The requested user's id
        required: true
        type: integer
      responses:
        201:
          description: job successfully sent
        400:
          description: invalid input, object invalid
        
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /Flamingo8/flamingops_base_api/1.0.0
schemes:
 - https