name: "[CD] DOCKER"

on:
  push:
    branches:
      - main
    paths:
      - '**/*.go'
      - '**/go.*'
jobs:
  DOCKER:
    name: DOCKER
    runs-on: ubuntu-latest
    steps:
      # checkout to current workspace
      - name: 1 - CHECKOUT
        uses: actions/checkout@v2

        # login to container registry
      - name: 2 - LOGIN TO GHCR.IO
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

        # build and push the app with given file and tag
      - name: 3 - BUILD + PUSH
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: build/package/sample-api/Dockerfile
          tags: ghcr.io/blyndusk/go-yave_sample-api:latest
          target: prod_build

        # output the logs
      - name: 4 - IMAGE DIGEST
        run: echo ${{ steps.docker_build.outputs.digest }}
